INSERT INTO ENDERECO (LOGRADOURO, NUMERO, BAIRRO, CIDADE, UF, CEP, COMPLEMENTO) VALUES ('Rua das Flores', '100', 'Jardim Primavera', 'São Paulo', 'SP', '01001-000', 'Apto 101');
INSERT INTO ENDERECO (LOGRADOURO, NUMERO, BAIRRO, CIDADE, UF, CEP, COMPLEMENTO) VALUES ('Av. Brasil', '2000', 'Centro', 'Rio de Janeiro', 'RJ', '20031-170', NULL);
INSERT INTO ENDERECO (LOGRADOURO, NUMERO, BAIRRO, CIDADE, UF, CEP, COMPLEMENTO) VALUES ('Rua do Sol', '50', 'Boa Viagem', 'Recife', 'PE', '51020-170', 'Casa');
INSERT INTO ENDERECO (LOGRADOURO, NUMERO, BAIRRO, CIDADE, UF, CEP, COMPLEMENTO) VALUES ('Av. Paulista', '1500', 'Bela Vista', 'São Paulo', 'SP', '01310-200', NULL);
INSERT INTO ENDERECO (LOGRADOURO, NUMERO, BAIRRO, CIDADE, UF, CEP, COMPLEMENTO) VALUES ('Rua da Paz', '300', 'Centro', 'Curitiba', 'PR', '80010-150', 'Fundos');

INSERT INTO ITEM (NOME, CATEGORIA) VALUES ('Cesta Básica', 'ALIMENTO_NAO_PERECIVEL');
INSERT INTO ITEM (NOME, CATEGORIA) VALUES ('Cobertor', 'ROUPA');
INSERT INTO ITEM (NOME, CATEGORIA) VALUES ('Água Mineral', 'ALIMENTO_NAO_PERECIVEL');
INSERT INTO ITEM (NOME, CATEGORIA) VALUES ('Kit Higiene', 'HIGIENE');
INSERT INTO ITEM (NOME, CATEGORIA) VALUES ('Mochila Escolar', 'INFANTIL');

INSERT INTO USUARIO (NOME_COMPLETO, USERNAME, EMAIL, SENHA, ENDERECO_ID) VALUES ('Guilherme Akira', 'gui', 'gui@email.com', 'senha123', 1);
INSERT INTO USUARIO (NOME_COMPLETO, USERNAME, EMAIL, SENHA, ENDERECO_ID) VALUES ('Alice Nunes', 'alice', 'alice@email.com', 'abc12345', 2);
INSERT INTO USUARIO (NOME_COMPLETO, USERNAME, EMAIL, SENHA, ENDERECO_ID) VALUES ('Anne Rezendes', 'anne', 'anne@email.com', 'anne321', 3);
INSERT INTO USUARIO (NOME_COMPLETO, USERNAME, EMAIL, SENHA, ENDERECO_ID) VALUES ('João Menk', 'jmenk', 'jmenk@email.com', 'cloud123', 4);
INSERT INTO USUARIO (NOME_COMPLETO, USERNAME, EMAIL, SENHA, ENDERECO_ID) VALUES ('Rennan Santos', 'resan', 'resan@email.com', 'java123', 5);

INSERT INTO PONTO_DISTRIBUICAO (TIPO, NOME, USUARIO_ID, ENDERECO_ID)VALUES ('RESIDENCIAL', 'Centro Comunitário Zona Leste', 1, 1);
INSERT INTO PONTO_DISTRIBUICAO (TIPO, NOME, USUARIO_ID, ENDERECO_ID)VALUES ('RESIDENCIAL', 'Van da Solidariedade', 2, 2);
INSERT INTO PONTO_DISTRIBUICAO (TIPO, NOME, USUARIO_ID, ENDERECO_ID)VALUES ('COMERCIAL', 'Igreja do Bem', 3, 3);
INSERT INTO PONTO_DISTRIBUICAO (TIPO, NOME, USUARIO_ID, ENDERECO_ID)VALUES ('COMERCIAL', 'TriaVan', 4, 4);
INSERT INTO PONTO_DISTRIBUICAO (TIPO, NOME, USUARIO_ID, ENDERECO_ID)VALUES ('COMERCIAL', 'Escola Municipal Esperança', 5, 5);

INSERT INTO ESTOQUE_ITEM (QUANTIDADE, DATA_ATUALIZACAO, ITEM_ID, PONTO_DISTRIBUICAO_ID)VALUES (50, TO_TIMESTAMP('2025-06-01 10:00:00', 'YYYY-MM-DD HH24:MI:SS'), 1, 1);
INSERT INTO ESTOQUE_ITEM (QUANTIDADE, DATA_ATUALIZACAO, ITEM_ID, PONTO_DISTRIBUICAO_ID)VALUES (100, TO_TIMESTAMP('2025-06-01 11:00:00', 'YYYY-MM-DD HH24:MI:SS'), 2, 1);
INSERT INTO ESTOQUE_ITEM (QUANTIDADE, DATA_ATUALIZACAO, ITEM_ID, PONTO_DISTRIBUICAO_ID)VALUES (100, TO_TIMESTAMP('2025-06-01 11:00:00', 'YYYY-MM-DD HH24:MI:SS'), 2, 2);
INSERT INTO ESTOQUE_ITEM (QUANTIDADE, DATA_ATUALIZACAO, ITEM_ID, PONTO_DISTRIBUICAO_ID)VALUES (30, TO_TIMESTAMP('2025-06-01 12:00:00', 'YYYY-MM-DD HH24:MI:SS'), 3, 3);
INSERT INTO ESTOQUE_ITEM (QUANTIDADE, DATA_ATUALIZACAO, ITEM_ID, PONTO_DISTRIBUICAO_ID)VALUES (75, TO_TIMESTAMP('2025-06-01 13:00:00', 'YYYY-MM-DD HH24:MI:SS'), 4, 4);
INSERT INTO ESTOQUE_ITEM (QUANTIDADE, DATA_ATUALIZACAO, ITEM_ID, PONTO_DISTRIBUICAO_ID)VALUES (25, TO_TIMESTAMP('2025-06-01 14:00:00', 'YYYY-MM-DD HH24:MI:SS'), 5, 5);